Fix error in error handling in negotiator-host 😕
This resolves the traceback below when negotiator-host is running
but 'crashes' because 'virsh list' fails because it can't connect
to libvirtd. This situation is still an unrecoverable error, but
the intention was for it to be an unrecoverable error that did
not produce a traceback...

  Traceback (most recent call last):
    File "/usr/lib/pl-negotiator-host/lib/negotiator_host/cli.py", line 117, in main
      action()
    File "/usr/lib/pl-negotiator-host/lib/negotiator_host/__init__.py", line 46, in __init__
      self.enter_main_loop()
    File "/usr/lib/pl-negotiator-host/lib/negotiator_host/__init__.py", line 53, in enter_main_loop
      self.update_workers()
    File "/usr/lib/pl-negotiator-host/lib/negotiator_host/__init__.py", line 62, in update_workers
      running_guests = set(find_running_guests())
    File "/usr/lib/pl-negotiator-host/lib/negotiator_host/__init__.py", line 270, in find_running_guests
      except ExternalCommandFailed:
  NameError: global name 'ExternalCommandFailed' is not defined